website/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index_view, name = 'index'),
    path('about/', views.about_view, name = 'about'),
    path('login/', views.login_view, name = 'login'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls', namespace = 'main')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls', namespace = 'meals')),
    path('weight/', include('weight.urls', namespace = 'weight')),
]

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Page Title{% endblock %} </title>
    <link rel="icon" type="image/x-icon" href={% block favicon_href %}"{% static 'favicon.ico' %}"{% endblock %}>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>
    <nav class="main-navbar">
      <ul>
        {% url 'main:index' as index %}
        {% url 'main:about' as about %}
        <li><a href="{{ index }}"{% if request.get_full_path == index %}class="current-location"{% endif %}>Home</a></li>
        <li><a href="{{ about }}"{% if request.get_full_path == about %}class="current-location"{% endif %}>About</a></li>
        {% if user.is_authenticated %}
        {% url 'weight:index' as weight %}
        <li><a href="{{ weight }}"{% if request.get_full_path == weight %} class="current-location"{% endif %}>Weight</a></li>
        <li><span>User: {{ user.get_username }}</span></li>
        <li>
          <form action="{% url 'logout' %}?next={% url 'main:index' %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="navbar-auth-button" value="Logout">
          </form>
        </li>
        {% else %}
        <li>
          <form action="{% url 'main:login' %}" method="GET">
            <input type="hidden" name="next" value="{{request.path}}">
            <input type="submit" class="navbar-auth-button" value="Login">
          </form>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% block content %}{% endblock %}
  {% block scripts %}{% endblock %}
  <a href="www.google.com">www.google.com</a>
  </body>
</html>